version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always

volumes:
  mariadb_data:
    driver_opts:
      type: none
      device: /home/yourlogin/data/mariadb
      o: bind

  wordpress_data:
    driver_opts:
      type: none
      device: /home/yourlogin/data/wordpress
      o: bind

networks:
  inception_network:
    driver: bridge
